# Welcome to Jekyll!
#

# Site settings
title: DTinTech
description: |
  Welcome to DTinTech. 
  We provide tools for business intelligence
  and Reporting.
owner: DTinTech
first_published: 2016 # if migrating another site, the year of your first publish
email: contact@dtintech.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dtintech.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/whispyy
  github: https://github.com/dtintech
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact.html
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
